### ISSUE TITLE
Einarbeitung SPS

### ISSUE THREAD

**Issue by PicusMaximus** [PicusMaximus/Industry4Dot0#2]

**Comment by DanielFriedrichAkaFreddy** [comment]
Yes

**Comment by DanielFriedrichAkaFreddy** [comment]
Letzte Woche in der Schule ging das sehr schleppend. Der PC da ist sehr langsam. Wir konnten leider keine Verbindung mit der SPS herstellen. Die Siemens Software hat zwar eine Funktion zum Suchen von Geräten im Netzwerk, aber da wurde nichts gefunden.

Auch direkt ansprechen über die IP ging nicht. (wobei uns die IP nur gesagt wurde, wer weiß ob es nicht doch was anderes war).

Zumindest haben wir uns in der Siemens Software etwas Orientieren können und welche Einstellungen wir brauchen.

Die snap7 Libary hat auch einen Server (https://snap7.sourceforge.net/snap7_server.html#snap7server) um eine SPS zu simulieren, wenn ich das richtig verstanden habe. 
Ich versuche das Zuhause mal. Dann könnten wir damit testen wenn wir keinen Zugriff zu einer SPS haben.
