### ISSUE TITLE
Fehlerhaften Dobot Home Befehl beheben

### ISSUE THREAD

**Issue by lennartabeln** [PicusMaximus/Industry4Dot0#35]

**Comment by mrvnbhmnn** [comment]
Ist behoben.
TeachIn Point in DobotStudio einlesen lassen.
Auf 250, 0, 0, 0 eingestellt, rechtsklick und SetHome --> Abfolge einmal ausführen
Danach kann der BaseCalibration Command wieder ausgeführt werden.
