### ISSUE TITLE
handshake: Login und GetJobs

### ISSUE THREAD

**Issue by PicusMaximus** [PicusMaximus/Industry4Dot0#48]

**Comment by nclaassen01** [comment]
@PicusMaximus  habe jetzt eigentlich alles für den Handshake vorbereitet. Musste eigentlich alle Endpunkte die wir so hatten einmal löschen und wieder neu schreiben 😅.  Die Endpunkte haben bislang eigentlich nur Placeholder bekommen, da wir halt noch nicht wirklich die Funktionen haben... Für einen Test sollte das aber reichen!
