### ISSUE TITLE
Kommunikation DoBot Monitor Testen

### ISSUE THREAD

**Issue by PicusMaximus** [PicusMaximus/Industry4Dot0#55]

**Comment by nclaassen01** [comment]
### Ergebnis
 Um einmal das Ergebnis des Testes festzuhalten.
- Die Kommunikation zwischen dem Dobot und dem Monitor funktioniert
- Die Kommunikation zwischen Monitor und dem Dobot hat aufgrund von Port- Problemen noch nicht funktioniert 

Nächste Woche müssen wir das auch noch einmal testen...
