### ISSUE TITLE
SPS Ansteuern

### ISSUE THREAD

**Issue by PicusMaximus** [PicusMaximus/Industry4Dot0#9]

**Comment by TritonOw** [comment]
@PicusMaximus Was soll hier gemacht werden. Dokumentation?

**Comment by PicusMaximus** [comment]
Das soll an sich schon ne doku sein einfach damit man nachvollziehen kann wann an was gearbeitet wurde.
Könnt das gerne noch mehr ausführen @TritonOw

**Comment by TritonOw** [comment]
08.02.2024:
    - Teilgruppe 1: 
    - Verbindung zur SPS hergestellt
        - Möglicher Hardware/Schnittstellen-Fehler
    - Probleme bei der Ausführung von Befehlen (Lesen/Schreiben aus DB z.B.)

**Comment by TritonOw** [comment]
15.02.2024
- Verbindung mithilfe von TCP und Paket snap7 gescheitert.
- C Variante probiert. Ebenfalls gescheitert
- Einarbeitung in Anwenderseiten und Webserver des PLC
-

**Comment by DanielFriedrichAkaFreddy** [comment]
Wir haben es heute mit snap7 endlich hingekriegt ohne Anwenderseite usw. Daten auf der SPS zu lesen und zu schreiben.

Weil wir snap7 schon halb aufgegeben hatten, haben wir es auch mit Anwenderseite usw. versucht das geht tatsächlich auch.


Wir werden mit snap7 jetzt weiter machen weil:
- kein Webserver der SPS nötig
- Fehlercodes der SPS werden direkt bei einer Aktion zurückgegeben
- weniger Komplexität
- flexibler im Umgang weil keine Anwenderseite angepasst werden muss

**Comment by DanielFriedrichAkaFreddy** [comment]
Tickets zu der Umsetzung mit Anwenderseite können dementsprechend geschlossen werden.
@HendrikulusMaximus
